---
title: "VolcanoMarkdown"
author: "K.Carver"
date: "2024-02-22"
output: html_document
---

#Set working directory
```{r}
# Start every session with setting your working directory

setwd("/cloud/project/SURP_RPlots-master") # Or however works for your computer

```

#Add libraries
```{r}
# Then make sure to add the libraries you'll be needing for the commands in this Script
library(ggplot2)
library(gplots)

```

#Read in the file
```{r}
# Next we want to read in the data 
# You need to include a path that goes to your files
# Uncomment if you want to include the entire path
#gene.transcript=read.csv("/Users/txc065/Downloads/SURP_RPlots-master/gene.description_sub.csv")

# Or if you're already in the same directory as your files you can just do
gene.transcript=read.csv("gene.description_sub.csv")

```

#Check amount of diemesions
```{r}
#Check how many dimensions the dataset has (rows and columns)
dim(gene.transcript)

```

#determine column names
```{r}
# Check what the column names are of your data
colnames(gene.transcript)

```

#Check the class of data
```{r}
# Also check what class of data you are using
class(gene.transcript)

```

#Plot Volcano Plot
```{r}
# including labeling red the genes that exceed an adjusted p-value of 0.05
plot(x = gene.transcript$log2FoldChange.L8_DOXvsL8., 
     y = -log10(gene.transcript$pvalue.L8_DOXvsL8.), 
     las = 1, 
     xlim = c(-4,4),
     ylim = c(0,200),
     col = ifelse(gene.transcript$padj.L8_DOXvsL8<=0.05, "red", "black"),
     xlab = "log2 Fold Change",
     ylab = "-log10(p-value)",
     main = "Volcano Plot of L8")

text(x = gene.transcript$log2FoldChange.L8_DOXvsL8., 
     y = -log10(gene.transcript$pvalue.L8_DOXvsL8.), 
     labels = ifelse(gene.transcript$padj.L8_DOXvsL8. <= 0.05 & abs(gene.transcript$log2FoldChange.L8_DOXvsL8.) >= 1.5, 
                     as.vector(gene.transcript$GeneName), NA),
     cex = 0.5, pos = 3)

legend("topright", 
       legend = c("significant"), 
       pt.bg = c("red"), 
       bty = "n",
       pch = 21, 
       cex = 0.8)

```


