#!/bin/bash

#This is my fruits script!

#The number of rows in fruits.txt
cat fruits.txt | wc -l

#Number of apples sold on Day1
cat fruits.txt | cut -f1 | grep "apple" -c -i

#Number of fruits sold on day 2
cat fruits.txt | cut -f2 | grep -v "Day2" -c -i
